services:
  rag_db_container:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: rag_db_user
      POSTGRES_PASSWORD: rag_db_pass
      POSTGRES_DB: rag_db
    volumes:
      - ./rag_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DESIGN: "hydra"

  backend:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.backend
    volumes:
      - ../backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - rag_db_container
